/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym;

/**
 *
 * @author Rifqi
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructor_menu = new javax.swing.JFrame();
        judul = new javax.swing.JLabel();
        training_menu = new javax.swing.JFrame();
        judul2 = new javax.swing.JLabel();
        workout_menu = new javax.swing.JFrame();
        judul3 = new javax.swing.JLabel();
        popupMenu1 = new java.awt.PopupMenu();
        btn_training = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_workoutProg = new javax.swing.JButton();
        btn_instructor = new javax.swing.JButton();

        judul.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("INSTRUKTUR");

        javax.swing.GroupLayout instructor_menuLayout = new javax.swing.GroupLayout(instructor_menu.getContentPane());
        instructor_menu.getContentPane().setLayout(instructor_menuLayout);
        instructor_menuLayout.setHorizontalGroup(
            instructor_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instructor_menuLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        instructor_menuLayout.setVerticalGroup(
            instructor_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instructor_menuLayout.createSequentialGroup()
                .addComponent(judul)
                .addGap(0, 327, Short.MAX_VALUE))
        );

        judul2.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        judul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul2.setText("Latihan soal");

        javax.swing.GroupLayout training_menuLayout = new javax.swing.GroupLayout(training_menu.getContentPane());
        training_menu.getContentPane().setLayout(training_menuLayout);
        training_menuLayout.setHorizontalGroup(
            training_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, training_menuLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        training_menuLayout.setVerticalGroup(
            training_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(training_menuLayout.createSequentialGroup()
                .addComponent(judul2)
                .addGap(0, 327, Short.MAX_VALUE))
        );

        judul3.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        judul3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul3.setText("Workout");

        javax.swing.GroupLayout workout_menuLayout = new javax.swing.GroupLayout(workout_menu.getContentPane());
        workout_menu.getContentPane().setLayout(workout_menuLayout);
        workout_menuLayout.setHorizontalGroup(
            workout_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workout_menuLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(judul3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        workout_menuLayout.setVerticalGroup(
            workout_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workout_menuLayout.createSequentialGroup()
                .addComponent(judul3)
                .addGap(0, 327, Short.MAX_VALUE))
        );

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        btn_training.setText("Training");
        btn_training.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trainingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GYM Sigma");

        btn_workoutProg.setText("WorkoutProg");
        btn_workoutProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_workoutProgActionPerformed(evt);
            }
        });

        btn_instructor.setText("Instructor");
        btn_instructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_instructorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_instructor)
                    .addComponent(btn_workoutProg)
                    .addComponent(btn_training)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btn_instructor)
                .addGap(18, 18, 18)
                .addComponent(btn_training)
                .addGap(18, 18, 18)
                .addComponent(btn_workoutProg)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_trainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trainingActionPerformed
      openTraining();  // TODO add your handling code here:
    }//GEN-LAST:event_btn_trainingActionPerformed

    private void btn_workoutProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_workoutProgActionPerformed
       openWorkout();// TODO add your handling code here:
    }//GEN-LAST:event_btn_workoutProgActionPerformed

    private void btn_instructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_instructorActionPerformed
      openNewFrame();  // TODO add your handling code here:
    }//GEN-LAST:event_btn_instructorActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_instructor;
    private javax.swing.JButton btn_training;
    private javax.swing.JButton btn_workoutProg;
    private javax.swing.JFrame instructor_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JFrame training_menu;
    private javax.swing.JFrame workout_menu;
    // End of variables declaration//GEN-END:variables

    private void openNewFrame() {
        this.instructor_menu.setVisible(true);
        this.instructor_menu.setTitle("Instructor Menu");
        this.instructor_menu.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.instructor_menu.setSize(300, 200);
    }

    private void openTraining() {
        this.training_menu.setVisible(true);
        this.training_menu.setTitle("Training Menu");
        this.training_menu.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.training_menu.setSize(300, 200);
    }

    private void openWorkout() {
        this.workout_menu.setVisible(true);
        this.workout_menu.setTitle("Training Menu");
        this.workout_menu.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.workout_menu.setSize(300, 200);
    }
}
